FROM apache/spark:3.5.1-scala2.12-java11-python3-ubuntu

USER root

WORKDIR ${SPARK_HOME}
ENV PATH="/opt/spark/sbin:/opt/spark/bin:${PATH}"

ENV SPARK_VERSION_SHORT=3.5
ENV SPARK_VERSION=3.5.1
ENV AWS_SDK_VERSION=1.12.773
ENV HADOOP_AWS_VERSION=3.3.4
ENV SPARK_HADOOP_CLOUD=2.12
ENV ICEBERG_VERSION=1.6.0
ENV AWS_SDK_BUNDLE_VERSION=2.20.18

# ----------------------------
# Dependências do sistema
# ----------------------------
RUN apt-get update -y && apt-get install -y \
    curl wget git zsh build-essential python3-dev \
    && rm -rf /var/lib/apt/lists/*

# ----------------------------
# Hadoop + AWS Jars
# ----------------------------
RUN curl -sSL https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar \
    -o ${SPARK_HOME}/jars/hadoop-aws-${HADOOP_AWS_VERSION}.jar \
 && curl -sSL https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_SDK_VERSION}/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar \
    -o ${SPARK_HOME}/jars/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar \
 && curl -sSL https://repo1.maven.org/maven2/org/apache/spark/spark-hadoop-cloud_${SPARK_HADOOP_CLOUD}/${SPARK_VERSION}/spark-hadoop-cloud_${SPARK_HADOOP_CLOUD}-${SPARK_VERSION}.jar \
    -o ${SPARK_HOME}/jars/spark-hadoop-cloud_${SPARK_HADOOP_CLOUD}-${SPARK_VERSION}.jar

# ----------------------------
# Iceberg Jars
# ----------------------------
RUN curl -sSL https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-${SPARK_VERSION_SHORT}_2.12/${ICEBERG_VERSION}/iceberg-spark-runtime-${SPARK_VERSION_SHORT}_2.12-${ICEBERG_VERSION}.jar \
    -o ${SPARK_HOME}/jars/iceberg-spark-runtime-${SPARK_VERSION_SHORT}_2.12-${ICEBERG_VERSION}.jar \
 && curl -sSL https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/${AWS_SDK_BUNDLE_VERSION}/bundle-${AWS_SDK_BUNDLE_VERSION}.jar \
    -o ${SPARK_HOME}/jars/aws-bundle-${AWS_SDK_BUNDLE_VERSION}.jar \
 && curl -sSL https://repo1.maven.org/maven2/software/amazon/awssdk/url-connection-client/${AWS_SDK_BUNDLE_VERSION}/url-connection-client-${AWS_SDK_BUNDLE_VERSION}.jar \
    -o ${SPARK_HOME}/jars/url-connection-client-${AWS_SDK_BUNDLE_VERSION}.jar

# ----------------------------
# Configuração do ZSH (opcional)
# ----------------------------
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true \
 && chsh -s /usr/bin/zsh \
 && echo "ZSH_THEME=robbyrussell" >> /root/.zshrc

ENV TERM=xterm

# ----------------------------
# Python + Jupyter
# ----------------------------
ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.7-src.zip:$PYTHONPATH

COPY ./jupyter/requirements.txt /opt/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/requirements.txt

COPY ./jupyter/jupyter_server_config.py /root/.jupyter/
COPY ./jupyter/themes.jupyterlab-settings /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/


# ----------------------------
# Configurações Spark
# ----------------------------
COPY ./spark-defaults-iceberg.conf /opt/spark/conf/spark-defaults.conf
COPY ./spark-env.sh /opt/spark/conf/spark-env.sh

# ----------------------------
# EntryPoint
# ----------------------------
CMD ["/bin/bash"]
