version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iceber-net   # <- só referencia a rede aqui

volumes:
  postgres_data:

networks:
  iceber-net:
    driver: bridge   # <- define o driver aqui, fora do serviço
